version: "3.9"
services:
  backend:
    build:
      context: ./backend
    container_name: library-backend
    environment:
      - PORT=4000
      - AUTH_TOKEN=${AUTH_TOKEN:-sk_demo_token_123}
      - UPLOAD_DIR=/app/uploads
      - DB_PATH=/app/database/db.sqlite
    volumes:
      - uploads:/app/uploads
      - db:/app/database
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:4000/health >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
    container_name: library-frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "5173:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  uploads:
  db:
